// <auto-generated />
using System;
using CBSExam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CBSExam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CBSExam.Models.Message", b =>
                {
                    b.Property<int>("messageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("messageID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("CBSExam.Models.SentMessage", b =>
                {
                    b.Property<int>("sentMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("confirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateSent")
                        .HasColumnType("datetime2");

                    b.Property<int>("messageID")
                        .HasColumnType("int");

                    b.HasKey("sentMessageID");

                    b.HasIndex("messageID");

                    b.ToTable("SentMessage");
                });

            modelBuilder.Entity("CBSExam.Models.SentMessage", b =>
                {
                    b.HasOne("CBSExam.Models.Message", "message")
                        .WithMany()
                        .HasForeignKey("messageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("message");
                });
#pragma warning restore 612, 618
        }
    }
}
